INSERT INTO motivational_quotes (quote, quote_bn, author) VALUES
('Verily, with hardship comes ease.', 'নিশ্চয়ই কষ্টের সাথে স্বস্তি আছে।', 'Quran 94:6'),
('And whoever puts their trust in Allah, He will be enough for them.', 'যে আল্লাহর উপর ভরসা করে, তিনি তার জন্য যথেষ্ট।', 'Quran 65:3'),
('So remember Me, I will remember you.', 'তোমরা আমাকে স্মরণ করো, আমি তোমাদের স্মরণ করব।', 'Quran 2:152'),
('Indeed, Allah is with the patient.', 'নিশ্চয়ই আল্লাহ ধৈর্যশীলদের সাথে আছেন।', 'Quran 2:153'),
('The best among you are those who learn the Quran and teach it.', 'তোমাদের মধ্যে সর্বোত্তম সে যে কুরআন শেখে এবং শেখায়।', 'Prophet Muhammad ﷺ'),
('Take advantage of five before five: your youth before old age, your health before sickness, your wealth before poverty, your free time before busyness, and your life before death.', 'পাঁচটি জিনিসকে পাঁচটির আগে মূল্যায়ন করো: যৌবনকে বার্ধক্যের আগে, স্বাস্থ্যকে অসুস্থতার আগে, সম্পদকে দারিদ্র্যের আগে, অবসরকে ব্যস্ততার আগে এবং জীবনকে মৃত্যুর আগে।', 'Prophet Muhammad ﷺ'),
('Whoever treads a path seeking knowledge, Allah will make easy for him the path to Paradise.', 'যে ব্যক্তি জ্ঞান অর্জনের পথে চলে, আল্লাহ তার জন্য জান্নাতের পথ সহজ করে দেন।', 'Prophet Muhammad ﷺ'),
('The strong believer is better than the weak believer, but there is goodness in both.', 'শক্তিশালী মুমিন দুর্বল মুমিনের চেয়ে উত্তম, তবে উভয়ের মধ্যেই কল্যাণ আছে।', 'Prophet Muhammad ﷺ'),
('Be in this world as if you were a stranger or a traveler.', 'দুনিয়াতে এমনভাবে থাকো যেন তুমি একজন অপরিচিত বা পথিক।', 'Prophet Muhammad ﷺ'),
('Discipline is the bridge between goals and accomplishment.', 'শৃঙ্খলা হলো লক্ষ্য এবং সফলতার মধ্যকার সেতু।', 'Jim Rohn'),
('The only way to do great work is to love what you do.', 'মহৎ কাজ করার একমাত্র উপায় হলো তুমি যা করো তা ভালোবাসা।', 'Steve Jobs'),
('Success is not final, failure is not fatal: it is the courage to continue that counts.', 'সফলতা চূড়ান্ত নয়, ব্যর্থতা মারাত্মক নয়: চালিয়ে যাওয়ার সাহসই গুরুত্বপূর্ণ।', 'Winston Churchill'),
('Your time is limited, do not waste it living someone else''s life.', 'তোমার সময় সীমিত, অন্যের জীবন যাপন করে এটি নষ্ট করো না।', 'Steve Jobs'),
('The secret of getting ahead is getting started.', 'এগিয়ে যাওয়ার রহস্য হলো শুরু করা।', 'Mark Twain'),
('And We have certainly made the Quran easy to remember. So is there anyone who will be mindful?', 'আমি কুরআনকে সহজ করে দিয়েছি উপদেশ গ্রহণের জন্য। অতএব, কোনো উপদেশ গ্রহণকারী আছে কি?', 'Quran 54:17'),
('Indeed, the prayer prohibits immorality and wrongdoing.', 'নিশ্চয়ই নামাজ অশ্লীলতা ও মন্দ কাজ থেকে বিরত রাখে।', 'Quran 29:45'),
('And seek help through patience and prayer.', 'ধৈর্য ও সালাতের মাধ্যমে সাহায্য প্রার্থনা করো।', 'Quran 2:45'),
('Do not lose hope in the mercy of Allah.', 'আল্লাহর রহমত থেকে নিরাশ হয়ো না।', 'Quran 39:53'),
('Allah does not burden a soul beyond that it can bear.', 'আল্লাহ কোনো আত্মাকে তার সাধ্যের বাইরে বোঝা দেন না।', 'Quran 2:286'),
('He who has health has hope, and he who has hope has everything.', 'যার স্বাস্থ্য আছে তার আশা আছে, আর যার আশা আছে তার সবকিছু আছে।', 'Arabic Proverb')